# Display user being processed
- name: Display viewer user information
  debug:
    msg: "Creating viewer user: {{ viewer_user.name }}"
  tags:
    - pgsql-all
    - pgsql-create-viewers

# Create the viewer user
- name: create viewer user
  postgresql_user:
    db: postgres
    name: "{{ viewer_user.name }}"
    password: "{{ viewer_user.password }}"
    port: "{{ db_main.port }}"
    encrypted: yes
  tags:
    - pgsql-all
    - pgsql-create-viewers

# Grant viewers role to user
- name: Grant role to app user
  become: yes
  become_user: postgres
  shell: psql -p {{ db_main.port }} postgres -U postgres -Atc "GRANT viewers TO {{ viewer_user.name }};"
  tags:
    - pgsql-all
    - pgsql-create-viewers

