
- name: Setup gpg key for pgdg-{{ db_ver }} {{ ansible_os_family }} {{ ansible_distribution_major_version }}
  template:
    src: templates/RPM-GPG-KEY-PGDG
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG-{{ db_ver }}

# - name: Import gpg key for pgdg-{{ db_ver }} {{ ansible_os_family }} {{ ansible_distribution_major_version }}
#   rpm_key:
#     state: present
#     key: https://ftp.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-{{ db_ver }}

- name: Add repo pgdg-{{ db_ver }}-{{ ansible_os_family }}{{ ansible_distribution_major_version }}
  become: true
  become_user: root
  become_method: sudo
  yum_repository:
    name: pgdg-{{ db_ver }}-{{ ansible_os_family }}{{ ansible_distribution_major_version }}
    description: PostgreSQL {{ db_version }} - {{ ansible_os_family }} {{ ansible_distribution_major_version }}
    baseurl: https://download.postgresql.org/pub/repos/yum/{{ db_version }}/redhat/rhel-$releasever-$basearch
    enabled: yes
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG-{{ db_ver }}
    gpgcheck: yes
    priority: "5"
