---

- name: set name for the main db sql file
  set_fact:
    local_db_schema: "{{ schema_path }}/{{ schema_path_suffix }}/{{ corezoid_release }}/init/{{ local_db }}.sql"
    remote_db_schema: "/tmp/{{ local_db }}_{{ corezoid_release }}.sql"
    current_remote_db_schema: "/tmp/{{ local_db }}_current.sql"
  when: local_db | regex_replace('[0-9]+$', '') != 'cp'
  tags:
  - debug-tunnel-var
  - pgsql-all
  - pgsql-diff

- name: set name for the shard's sql file
  set_fact:
    local_db_schema: "{{ schema_path }}/{{ schema_path_suffix }}/{{ corezoid_release }}/init/cp.sql"
    remote_db_schema: "/tmp/cp_{{ corezoid_release }}.sql"
    current_remote_db_schema: "/tmp/{{ local_db }}_current.sql"
  when: local_db | regex_replace('[0-9]+$', '') == 'cp'
  tags:
  - debug-tunnel-var
  - pgsql-all
  - pgsql-diff

- name: Copy ApgDiff
  copy:
    src: "{{ schema_path }}/{{ schema_path_suffix }}/{{ item }}"
    dest: "/tmp/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - "apgdiff-2.4.jar"
  tags:
  - pgsql-all
  - pgsql-diff
  - pgsql-diff-copy-apgdiff-jar

- name: Copy new schema for {{ local_db }}
  copy:
    src: "{{ local_db_schema }}"
    dest: "{{ remote_db_schema }}"
    owner: root
    group: root
    mode: 0644
  tags:
  - pgsql-all
  - pgsql-diff
  - pgsql-diff-copy-new-schemas

- name: Create schema-only dump for {{ local_db }}
  become: yes
  become_user: postgres
  shell: pg_dump -p {{ db_main.port }} -s {{ local_db }} > {{ current_remote_db_schema }}
  tags:
  - pgsql-all
  - pgsql-diff
  - pgsql-diff-create-current-schemas

- name: Create diff for {{ local_db }}
  become: yes
  become_user: postgres
  shell: java -jar /tmp/apgdiff-2.4.jar {{ current_remote_db_schema }} {{ remote_db_schema }} > /tmp/{{ local_db }}_diff.sql
  tags:
  - pgsql-all
  - pgsql-diff
  - pgsql-diff-create-sql-diff

- name: Apply diff for {{ local_db }}
  become: yes
  become_user: postgres
  shell: psql -p {{ db_main.port }} -d {{ local_db }} < /tmp/{{ local_db }}_diff.sql
  tags:
  - pgsql-all
  - pgsql-diff
  - pgsql-diff-apply-diff

- name: Copy grants file
  copy:
    src: "{{ schema_path }}/{{ schema_path_suffix }}/grants.sql"
    dest: "/tmp/grants.sql"
    owner: root
    group: root
    mode: 0644
  tags:
  - pgsql-all
  - pgsql-diff
  - pgsql-diff-copy-grants

- name: Apply grants for {{ local_db }}
  become: yes
  become_user: postgres
  shell: psql -p {{ db_main.port }} -d {{ local_db }} < /tmp/grants.sql
  tags:
  - pgsql-all
  - pgsql-diff
  - pgsql-diff-apply-grants

