
- name: Create main dbs
  postgresql_db: >
    name={{ item }}
    login_host={{ db_main.host }}
    port={{ db_main.port }}
  with_items:
    - conveyor2
  tags:
    - pgsql-test

- name: create table api_callbacks
  postgresql_table:
    db: conveyor2
    login_host: "{{ db_main.host }}"
    port: "{{ db_main.port }}"
    name: api_callbacks
    columns:
    - conveyor_id integer NOT NULL
    - hash character(40) NOT NULL
    - data text
  tags:
    - pgsql-test

- name: Create indexies for api_callbacks
  postgresql_idx:
    db: conveyor2
    login_host: "{{ db_main.host }}"
    port: "{{ db_main.port }}"
    table: api_callbacks
    columns: hash
    idxtype: btree
    name: api_callbacks_hash_id