- name: Yum clean all
  command: yum clean all
#  args:
#    warn: false
  tags:
    - conf_agent_server-all
    - conf_agent_server-app
    - conf_agent_server-install

- name: Install package conf_agent_server
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
    disablerepo: "*"
    enablerepo: "aws-corezoid"
  with_items:
    - conf_agent_server-{{ corezoid_release_app_version.conf_agent_server }}
  tags:
    - conf_agent_server-all
    - conf_agent_server-app
    - conf_agent_server-install

- name: add log directory
  file: path={{ top_dir }}/erlang/{{ item }}/log owner={{ app_user }} group={{ app_user }} state=directory mode=0700
  with_items:
    - conf_agent_server
  tags:
    - conf_agent_server-all
    - conf_agent_server-app
    - conf_agent_server-install

- name: fix permission
  file:
    path: "{{ top_dir }}/erlang/{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    state: directory
    mode: '0700'
    recurse: yes
  with_items:
    - conf_agent_server
  tags:
    - conf_agent_server-all
    - conf_agent_server-app
    - conf_agent_server-install

- name: Create conf_agent_server config file
  template:
    src: "templates/{{ corezoid_release }}-{{ item }}.config.j2"
    dest: "{{ conf_agent_server_config }}"
  with_items:
    - conf_agent_server
  tags:
    - conf_agent_server-all
    - conf_agent_server-app
    - conf_agent_server-config-file

- name: Fix permission to conf_agent_server.config file
  file: state=file path={{ conf_agent_server_config }} owner={{ app_user }} group={{ app_user }} mode=0500
  with_items:
    - conf_agent_server
  when: ansible_host != "127.0.0.1"
  tags:
    - conf_agent_server-all
    - conf_agent_server-app
    - conf_agent_server-config-file

- name: Setup app systemd
  template: src=templates/{{ item }}.service.j2 dest=/etc/systemd/system/{{ item }}.service owner=root group=root mode=0644
  with_items:
    - conf_agent_server
  tags:
    - conf_agent_server-all
    - conf_agent_server-app
    - conf_agent_server-systemd
  when:
    - ansible_os_family == "RedHat" or ansible_os_family == "CentOS"
    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9"

- name: Enable conf_agent_server to survive reboot
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
    # no_block: yes
  with_items:
    - conf_agent_server
  tags:
    - conf_agent_server-all
    - conf_agent_server-app
    - conf_agent_server-initd
    - conf_agent_server-initd-start

- name: Create monit file
  template: src=templates/{{ item }}.monit.j2 dest=/etc/monit.d/{{ item }} owner=root group=root mode=0600
  with_items:
    - conf_agent_server
  register: monit_file
  tags:
    - conf_agent_server-all
    - conf_agent_server-app
    - conf_agent_server-monit

- name: Reload monit if config file changed
  service:
    name: monit
    state: reloaded
  when: monit_file.changed
  tags:
    - conf_agent_server-all
    - conf_agent_server-app
    - conf_agent_server-monit
