CREATE ROLE appusers;
ALTER ROLE appusers WITH INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOBYPASSRLS;

CREATE ROLE viewers;
ALTER ROLE appusers WITH INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOBYPASSRLS;
CREATE ROLE internal_user;
ALTER ROLE internal_user WITH INHERIT NOCREATEROLE NOCREATEDB LOGIN NOBYPASSRLS PASSWORD 'internal_user_password';

GRANT appusers TO internal_user;
GRANT viewers TO zabbix;