---

- name: Refresh repository cache
  shell: yum clean all && yum makecache

#- name: Install the epel-release package
#  yum: name=epel-release state=present

- name: Create the repository for mongodb
  copy: src=mongodb-org-3.2.repo dest=/etc/yum.repos.d/mongodb-org-3.2.repo

- name: Install the mongodb package
  yum:
   state: present
   name:
    - policycoreutils-python
    - mongodb-org-mongos-{{mongodb_version}}
    - mongodb-org-shell-{{mongodb_version}}
    - mongodb-org-server-{{mongodb_version}}


#- name: Install the latest pymongo package
#  pip: name={{item}} state=latest
#  with_items:
#   - pip

- name: Enable port on SELinux
  seport:
    ports: "2700-2703,{{mongos_port}},{{mongoc_port}}"
    proto: tcp
    setype: mongod_port_t
    state: present
  when: ansible_selinux is defined and ansible_selinux != False and ansible_selinux.status == 'enabled'
    
- name: Create the mongod user
  user: name=mongod comment="MongoD"

- name: Create the data directory for the namenode metadata
  file: path={{ mongodb_datadir_prefix }} owner=mongod group=mongod state=directory setype=mongod_var_lib_t recurse=true

- name: Create log directory for mongodb
  file: path=/var/log/mongo state=directory owner=mongod group=mongod setype=mongod_log_t recurse=true

- name: Create run directory for mongodb
  file: path=/var/run/mongo state=directory owner=mongod group=mongod setype=mongod_var_run_t seuser=system_u recurse=true

- name: Create hosts file for local tests
  template: src="hosts.j2" dest="/etc/hosts" owner=root group=root backup=yes
