---
- name: Install Goss
  get_url: url=https://github.com/aelsabbahy/goss/releases/latest/download/goss-linux-amd64 dest=/usr/bin/goss
  tags:
    - goss_tests

- name: add exec to Goss
  file: dest=/usr/bin/goss mode="a+x"
  tags:
    - goss_tests
    -

- name: Creates directory for goss
  file:
    path: /etc/goss.d/
    state: directory
  tags:
    - goss_tests

- name: Copy goss tests
  template:
    dest: "/etc/goss.d/{{ item }}"
    src: "tests/{{ item }}"
    owner: root
    group: root
    mode: 755
  tags:
    - goss_tests
  with_items:
    - "capi.yml"

- name: Test capi
  command: goss --gossfile "/etc/goss.d/{{ item }}" validate
#    ignore_errors: yes
  with_items:
    - "capi.yml"
  tags:
    - goss_tests
