---
# defaults file for worker_converter

# RabbitMQ consumer settings
wc_rmq_exchange: "FinalTasksLogsExchange"
wc_rmq_queue_name: "FinalTasksLogsQ"
wc_rmq_queues_count: 4
wc_rmq_connections_per_queue: 2
wc_rmq_channels_per_connection: 2
wc_rmq_messages_prefetch: 20

# RabbitMQ GC settings
wc_rmq_gc_queues_regexp: "^FinalTasksLogs([0-9])+"

# Elasticsearch producer settings
wc_es_thread_count: 40
wc_es_timeout: 120
wc_es_interval_checking_buffer: 2
wc_es_bulk_send_after_time: 1
wc_es_bulk_count: 10

# Worker converter general
wc_memory_limit: 2073741824
wc_is_ready_port: 8390
wc_cluster_port: 5567

# lager settings
lager_console_backend: "info"
log_parts_count: 5
log_parts_size: 734003200

lager_error_size: "{{ log_parts_size }}"
lager_error_count: "{{ log_parts_count }}"

lager_info_size: "{{ log_parts_size }}"
lager_info_count: "{{ log_parts_count }}"

lager_crash_size: 10485760
lager_crash_count: "{{ log_parts_count }}"

lager_error_logger_redirect: "true"
lager_error_logger_hwm: 50
lager_async_threshold: 20
lager_async_threshold_window: 5
