- name: "Get limit by user_id"
  nodetool:
    action: eval
    command: limits:get_user_rate({{ user_id }})
    cookie: capi
    node:   capi@127.0.0.1
    nametype: longnames
  tags:
    - capi-limits-get-user-rate
  register: capi_limits_get_user_rate_result

- debug:
    msg: "{{ capi_limits_get_user_rate_result.stdout_lines }}"
  tags:
    - capi-limits-get-user-rate-debug

- name: "Set new limit for user_id"
  nodetool:
    action: eval
    command: limits:set_user_rate({{ user_id }},{{ new_limit }})
    cookie: capi
    node:   capi@127.0.0.1
    nametype: longnames
  tags:
    - capi-limits-set-user-rate
  register: capi_limits_set_user_rate_result

- debug:
    msg: "{{ capi_limits_set_user_rate_result.stdout_lines }}"
  tags:
    - capi-limits-set-user-rate-debug

# api_permitted:is_allowed(1, 14, 0, create).
