- name: "worker_redis:get_conveyor_owner2"
  nodetool:
    action: eval
    command: worker_redis:get_conveyor_owner2({{ conv_id }})
    cookie: worker
    node:   worker@127.0.0.1
    nametype: longnames
  register: worker_redis_get_conveyor_owner2
  tags:
    - worker-get-process-owner

- debug:
    msg: "{{ worker_redis_get_conveyor_owner2.stdout_lines }}"
  tags:
    - worker-get-process-owner-debug

- name: "conveyor_access:get_owner_id"
  nodetool:
    action: eval
    command: conveyor_access:get_owner_id({{ conv_id }})
    cookie: worker
    node:   worker@127.0.0.1
    nametype: longnames
  register: conveyor_access_get_owner_id
  tags:
    - worker-get-process-owner

- debug:
    msg: "{{ conveyor_access_get_owner_id.stdout_lines }}"
  tags:
    - worker-get-process-owner-debug

# worker_main_client:info(ShardId).
# worker_main_client:kill_workers(ConvId).
# synchronize_count:conv_sync(ConvId).

- name: "worker_main_client:kill_workers"
  nodetool:
    action: eval
    command: worker_main_client:kill_workers({{ shard_id }})
    cookie: worker
    node:   worker@127.0.0.1
    nametype: longnames
  register: worker_main_client_kill_workers
  tags:
    - synchronize-count-conv-sync

- debug:
    msg: "{{ worker_main_client_kill_workers.stdout_lines }}"
  tags:
    - synchronize-count-conv-sync

- name: "synchronize_count:conv_sync"
  nodetool:
    action: eval
    command: synchronize_count:conv_sync({{ conv_id }})
    cookie: worker
    node:   worker@127.0.0.1
    nametype: longnames
  register: synchronize_count_conv_sync
  tags:
    - synchronize-count-conv-sync  

- debug:
    msg: "{{ synchronize_count_conv_sync.stdout_lines }}"
  tags:
    - synchronize-count-conv-sync
