---
# handlers file for http-worker

- name: Reload monit if config file changed
  service:
    name: monit
    state: reloaded
  when: monit_file.changed or monit_file_old.changed
  tags:
    - http-worker-all
    - http-worker-monit