- debug:
    msg: "{{ ansible_distribution }}"
  tags:
    - postgresql-all
    - postgresql-repo
    - postgresql-getdist

- debug:
    msg: "{{ ansible_distribution_major_version }}"
  tags:
    - postgresql-all
    - postgresql-repo
    - postgresql-getdist

- debug:
    msg: "{{ ansible_default_ipv4.address }}"
  tags:
    - postgresql-all
    - postgresql-repo
    - postgresql-getdist

- debug:
    msg: "{{ ansible_os_family }}"
  tags:
    - postgresql-all
    - postgresql-repo
    - postgresql-getdist

- debug:
    msg: "{{ ansible_distribution_version }}"
  tags:
    - postgresql-all
    - postgresql-repo
    - postgresql-getdist


- name: Add PgSQL96 repo for AWS
  import_tasks: corezoid-repos-pgdg-96-ami201503.yml
  when:
    - pgdg13_aws is defined
    - ansible_distribution == "Amazon"
  tags:
    - postgresql-all
    - postgresql-repo
    - postgresql-repo-13-amzn1

# - name: Add PgSQL96 repo for RHEL/CentOS 6
#   import_tasks: corezoid-repos-pgdg-RHEL.yml
#   when:
#     - pgdg96 is defined
#     - ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "OracleLinux"
#     - ansible_distribution_major_version == "6"
#   tags:
#     - postgresql-all
#     - postgresql-repo
#     - postgresql-repo-96-el6

#- name: Add PgSQL96 repo for RHEL/CentOS 7/8
#  yum:
#    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
#    state: installed
#  when:
#    - pgdg96 is defined
#    - ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "OracleLinux"
#    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8"
#  tags:
#    - postgresql-all
#    - postgresql-repo
#    - postgresql-repo-96-el7

- name: Add PgSQL12 repo for RHEL/CentOS 7/8
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: installed
  when:
    - pgdg12 is defined
    - ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "OracleLinux"
    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8"
  tags:
    - yum-all
    - postgresql-repo
    - postgresql-repo-12-el7

- name: Add PgSQL13 repo for RHEL/CentOS 7/8
  import_tasks: corezoid-repos-pgdg-RHEL.yml
  when:
    - pgdg13 is defined
    - ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "OracleLinux"
    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8"
#  yum:
#    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
#    state: installed
  tags:
    - yum-all
    - postgresql-repo
    - postgresql-repo-13-el7

- name: Disable the built-in PostgreSQL module
  command: dnf -qy module disable postgresql
  args:
    warn: false
  when:
    - pgdg96 is defined or pgdg12 is defined or pgdg13 is defined
    - ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "OracleLinux"
    - ansible_distribution_major_version == "8"
  tags:
    - yum-all
    - postgresql-repo
    - postgresql-repo-96-el8
    - postgresql-repo-12-el8
