GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO appusers;
GRANT SELECT,UPDATE ON ALL SEQUENCES IN SCHEMA public TO appusers;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO viewers;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO viewers;
