---
# handlers file for monit
- name: Reload monit if config file changed
  service:
    name: monit
    state: reloaded
  when: monit_file.changed
  tags:
    - api-multipart-all
    - api-multipart-monit
