---
# tasks file for http-worker

# Clean YUM cache to ensure fresh package metadata
# Removes all cached package data to prevent installation issues
- name: Yum clean all
  command: yum clean all
  #  args:
  #    warn: false
  tags:
    - http-worker-all
    - http-worker-install

# Install HTTP Worker application package
# Installs or updates the http-worker package from AWS Corezoid repository with specific version
- name: Install http-worker app
  yum:
    name: "{{ item }}-{{http_worker.version}}"
    state: present
    update_cache: yes
    disablerepo: "*"
    enablerepo: "aws-corezoid"
  with_items:
    - http-worker
  tags:
    - http-worker-all
    - http-worker-install

# Create log directory for HTTP Worker
# Sets up a directory for application logs with appropriate permissions
- name: Add log directory
  file: path={{ top_dir }}/erlang/{{ item }}/log owner={{ app_user }} group={{ app_user }} state=directory
  with_items:
    - http-worker
  tags:
    - http-worker-all
    - http-worker-install

# Set secure permissions for application directory
# Ensures all HTTP Worker files have proper ownership and restricted access
- name: Fix permission for http-worker folder
  file: path={{ top_dir }}/erlang/{{ item }} owner={{ app_user }} group={{ app_user }} state=directory mode=0700 recurse=yes
  with_items:
    - http-worker
  tags:
    - http-worker-all
    - http-worker-install

# Create configuration directory
# Sets up a directory for storing application configuration files
- name: Make config folder
  file: path={{ conf_dir }} owner=root group=root state=directory mode=0755
  tags:
    - http-worker-all
    - http-worker-config

# Generate HTTP Worker configuration
# Creates the main configuration file using provided template
- name: Create http_worker.config
  template: src=templates/{{ corezoid_release }}-http_worker.config.j2 dest={{ http_worker.config }}
  with_items:
    - http-worker
  tags:
    - http-worker-all
    - http-worker-config
    - http-worker-config-file

# Set secure permissions for configuration file
# Restricts access to the configuration file for security on non-localhost systems
- name: Fix permission to http_worker.config file
  file: state=file path={{ http_worker.config }} owner={{ app_user }} group={{ app_user }} mode=0500
  when: ansible_host != "127.0.0.1"
  tags:
    - http-worker-all
    - http-worker-config
    - http-worker-config-file

# Configure systemd service
# Sets up the systemd service for automatic HTTP Worker management
- name: Create http-worker systemd
  template: src=templates/{{ item }}.service.j2 dest=/etc/systemd/system/{{ item }}.service owner=root group=root mode=0644
  with_items:
    - http-worker
  tags:
    - http-worker-all
    - http-worker-initd
    - http-worker-systemd
  when:
    - ansible_os_family == "RedHat" or ansible_os_family == "CentOS"
    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9"

# Check existence of systemd service directory
# Verifies if the systemd service configuration directory exists
- name: check http-worker.service.d folder
  stat:
    path: "/etc/systemd/system/http-worker.service.d"
  register: systemd_folder_check
  tags:
    - http-worker-all
    - http-worker-app
    - http-worker-systemd

# Configure systemd service directory and reload daemon
# Creates necessary systemd directories and refreshes systemd configuration
- name: Setup app systemd
  block:
    - name: Make folder for static content
      file:
        path: "/etc/systemd/system/{{ item }}.service.d"
        owner: root
        group: root
        state: directory
        mode: 0755
        recurse: yes
      with_items:
        - http-worker
    - name: Reload systemctl
      shell: systemctl daemon-reload
  when:
    - systemd_folder_check.stat.isreg is not defined
    - ansible_os_family == "RedHat" or ansible_os_family == "CentOS" or ansible_distribution == "Amazon"
    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "2" or ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9" or ansible_distribution_major_version == "2023"
  tags:
    - http-worker-all
    - http-worker-app
    - http-worker-systemd

# Verify systemd service directory status
# Double-checks the systemd service directory configuration
- name: check http-worker.service.d folder
  stat:
    path: "/etc/systemd/system/http-worker.service.d"
  register: systemd2_folder_check
  tags:
    - http-worker-all
    - http-worker-app
    - http-worker-systemd

# Install systemd service limits and reload configuration
# Sets up resource limits for the service and refreshes systemd
- name: Setup app systemd
  block:
    - name: Install limits file
      template: src=templates/limits dest=/etc/systemd/system/{{ item }}.service.d/limits.conf owner=root group=root mode=0644
      with_items:
        - http-worker
    - name: Reload systemctl
      shell: systemctl daemon-reload
  when:
    # - systemd2_folder_check.stat.isreg
    - ansible_os_family == "RedHat" or ansible_os_family == "CentOS" or ansible_distribution == "Amazon"
    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "2" or ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9" or ansible_distribution_major_version == "2023"
  tags:
    - http-worker-all
    - http-worker-app
    - http-worker-systemd

# Start HTTP Worker service
# Initiates the HTTP Worker service and ensures systemd is up to date
- name: Start http-worker
  systemd:
    state: started
    daemon_reload: yes
    name: http-worker
  when:
    - ansible_os_family == "RedHat" or ansible_os_family == "CentOS"
    - ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9"

# Enable and start HTTP Worker service
# Ensures the service starts automatically on boot and is running
- name: Enable http-worker to survive reboot
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
    # no_block: yes
  with_items:
    - http-worker
  tags:
    - http-worker-all
    - http-worker-initd
    - http-worker-initd-start

# Check for legacy Monit configuration
# Verifies if old monitoring configuration exists
- name: Check that old monit file for http_worker exists
  stat:
    path: "/etc/monit.d/{{ item }}"
  with_items:
    - http_worker
  register: stat_result
  tags:
    - http-worker-all
    - http-worker-monit

# Display Monit configuration status
# Shows the current state of the Monit configuration file
- name: current stat_result
  debug: msg={{ stat_result.results[0].stat.exists }}
  tags:
    - http-worker-all
    - http-worker-monit

# Remove legacy Monit configuration
# Cleans up old monitoring configuration files if present
- name: Delete old monit file for http_worker
  file:
    path: "/etc/monit.d/{{ item }}"
    state: absent
  with_items:
    - http_worker
  when: stat_result.results[0].stat.exists == true
  tags:
    - http-worker-all
    - http-worker-monit

# Create new Monit monitoring configuration
# Sets up monitoring for the HTTP Worker service
- name: Create monit file
  template: src=templates/{{ item }}.monit.j2 dest=/etc/monit.d/{{ item }} owner=root group=root mode=0600
  with_items:
    - http-worker
  register: monit_file
  tags:
    - http-worker-all
    - http-worker-monit

# Ensure Monit service is running
# Starts the Monit service if it's not already running
- name: Start service monit, if not started
  service:
    name: monit
    state: started
  tags:
    - http-worker-all
    - http-worker-monit

# Reload Monit configuration if changed
# Applies any changes to the Monit monitoring setup
- name: Reload service monit, if monit files changed
  service:
    name: monit
    state: reloaded
  when: monit_file.results[0].changed == true
  tags:
    - http-worker-all
    - http-worker-monit

# Configure worker ID rotation
# Sets up automatic rotation of worker ID for security in autoscale environments
- name: Change http-worker-id in config
  cron:
    special_time: reboot
    name: "Change http-worker-id in config"
    user: "root"
    job: "rand_id=$(pwgen -n 20 -s 1); sed -i -e \"s/{{ http_worker_id }}/${rand_id}/g\" {{ http_worker.config }}"
  when: autoscale
  tags:
    - http-worker-all
    - http-worker-cron

# Enable Monit monitoring for HTTP Worker
# Activates Monit monitoring for the HTTP Worker service
- name: Monitor http-worker by Monit
  monit:
    name: http-worker
    state: monitored
  with_items:
    - http-worker
  tags:
    - http-worker-all
    - http-worker-monit
    - http-worker-monit-1