---
#-------------git_call-------------#

- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
    disablerepo: "*"
    enablerepo: "aws-corezoid"
  with_items:
    # - git
    - "git-code-hub-{{ corezoid_release_app_version.git_code_hub }}"
    - "js-code-hub-{{ corezoid_release_app_version.js_code_hub }}"
    - "js-worker-{{ corezoid_release_app_version.js_worker }}"
  tags:
    - git_call-all
    - git_call-app
    - git_call-install

- name: Create git_call.config file
  template: src=templates/{{ item }}.config.j2 dest={{ top_dir }}/conf/{{ item }}/config/default.json
  with_items:
    - git-code-hub
    - js-code-hub
    - js-worker
  tags:
    - git_call-all
    - git_call-app
    - git_call-config
    - git_call-config-file

# - name: Fix permission to config file
#   file: state=file path={{ git_call.config }} owner={{ app_user }} group={{ app_user }} mode=0600
#   with_items:
#     - git_call
#   when: ansible_host != "127.0.0.1"
#   tags:
#     - git_call-all
#     - git_call-app
#     - git_call-config
#     - git_call-config-file

# - name: Setup app systemd
#   template: src=templates/gitcall_app.service.j2 dest=/etc/systemd/system/{{ item }}.service owner=root group=root mode=0644
#   with_items:
#     - git-code-hub
#     - js-code-hub
#     - js-worker
#   tags:
#     - git_call-all
#     - git_call-app
#     - git_call-initd
#   when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Enable git_call to survive reboot
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
    # no_block: yes
  with_items:
    - git-code-hub
    - js-code-hub
    - js-worker
  tags:
    - git_call-all
    - git_call-app
    - git_call-initd

- name: Create monit file
  template: src=templates/gitcall_app.monit.j2 dest=/etc/monit.d/{{ item }} owner=root group=root mode=0600
  with_items:
    - git-code-hub
    - js-code-hub
    - js-worker
  register: monit_file
  tags:
    - git_call-all
    - git_call-app
    - git_call-monit

- name: Reload monit if config file changed
  service:
    name: monit
    state: reloaded
  when: monit_file.changed
  tags:
    - git_call-all
    - git_call-app
    - git_call-monit
