---
- debug:
    msg: |
      System Information:
      ==================
      Hostname: {{ ansible_hostname }}
      IP: {{ ansible_default_ipv4.address }}
      CPU count: {{ ansible_processor_vcpus }}
      Total memory: {{ ansible_memtotal_mb }} MB
      
      Distribution Information:
      =======================
      Distribution: {{ ansible_distribution }}
      Distribution version: {{ ansible_distribution_version }}
      Major version: {{ ansible_distribution_major_version }}
      OS family: {{ ansible_os_family }}
  tags:
    - yum-all
    - yum-debug
    - getdist

- name: Enable exta repos for Amazon linux 2
  block:
    - name: enable epel
      shell: amazon-linux-extras install epel -y
    - name: Install epel-release repo
      yum:
        name: epel-release
        state: latest
        update_cache: yes
      notify: yum-clean-metadata
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"
  tags:
   - yum-all
   - yum-epel-repo-install

- name: Add Corezoid Repo
  template:
    src: "templates/corezoid-Amazon-aws.repo.j2"
    dest: "/etc/yum.repos.d/corezoid-prod.repo"
    owner: root
    group: root
    mode: '0644'
  tags:
    - yum-all
    - yum-corezoid-repo



