- name: Set Distribution Version
  set_fact:
    distr_version: 7
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags:
    - yum-middleware-system-repo-install

- name: Set Distribution Version
  set_fact:
    distr_version: 7
  when: (ansible_distribution == "RedHat" or ansible_distribution == "OracleLinux")and ansible_distribution_major_version == "7"
  tags:
    - yum-middleware-system-repo-install

- name: Set Distribution Version
  set_fact:
    distr_version: 8
  when: (ansible_distribution == "CentOS" or ansible_distribution == "OracleLinux")and ansible_distribution_major_version == "8"
  tags:
    - yum-middleware-system-repo-install

- name: Set Distribution Version
  set_fact:
    distr_version: 7
  when:
    - ansible_distribution == "Amazon"
    - ansible_distribution_major_version == "2"
  tags:
    - yum-middleware-system-repo-install

- name: Set Distribution Version
  set_fact:
    distr_version: 2023
  when:
    - ansible_distribution == "Amazon"
    - ansible_distribution_major_version == "2023"
  tags:
    - yum-middleware-system-repo-install

- debug:
    msg: "{{ distr_version }}"
  tags:
    - yum-middleware-system-repo-install

- name: Add Middleware System Repo
  template:
    src: templates/middleware-system.repo.j2
    dest: /etc/yum.repos.d/middleware-system.repo
    owner: root
    group: root
    mode: '0644'
  tags:
    - yum-all
    - yum-middleware-system-repo-install